version: '3.8'

services:
  demo-api:
    image: postgres:latest
    container_name: postgres_container_demo_api
    restart: always
    environment:
      POSTGRES_USER: sofiane
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invoices
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer-demo-api:
    image: adminer
    container_name: adminer_container_demo_api
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
